config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end


  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  post 'simple_pages/thank_you'

  post 'payments/create'

  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }

  # after_create_commit { CommentUpdateJob.perform_later(self, self.user) }

  scope :rating_desc, -> { order(rating: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @product, notice: 'Review was created.' }
        format.json { render :show, status: :created, location: @product }
        format.js
        # ActionCable.server.broadcast 'product_channel', comment: "Hello World", average_rating: 5
        # ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        # ProductChannel.broadcast_to @product.id, comment: @comment, average_rating: @product.average_rating
        # ProductChannel.broadcast_to @product.id, comment: CommentsController.render(partial: 'comments/comment', locals: {comment: @comment}), average_rating: @product.average_rating
        ProductChannel.broadcast_to @product.id, comment: CommentsController.render(partial: 'comments/comment', locals: {comment: @comment, current_user: current_user}), average_rating: @product.average_rating
        # This was moved to comment_update_job for ActiveJob example
      else
        format.html { redirect_to @product, alert: 'Review not saved.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end

end

# left off at "Views", about 1/4 the way down 5.8

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
  <!-- <%# if signed_in? && current_user.admin? %> -->
  <% if current_user && current_user.admin? %> <!-- workaround for devise because current user is not available when rendered outside ctrl actions -->
  <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/comments/create.js.erb
// $("#new_comment").hide();
$("#new_comment").html("Thank you for the review!")
// $(".product-reviews").prepend("<%= j render @comment %>");
$("#average-rating").attr('data-score', "<%= @product.average_rating %>");
refreshRating();