config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end


  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  post 'simple_pages/thank_you'

  post 'payments/create'

  root 'simple_pages#landing_page'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nameofapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", simple_pages_about_path %></li>
      <li><%= link_to "Contact", simple_pages_contact_path %></li>
      <li><%= link_to "Orders", orders_path %></li>
      <li><%= current_user.first_name if current_user %>, (id = <%= current_user.id if current_user %>)</li>
      <li>
        <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        <% else %>
        <%= link_to('Login', new_user_session_path) %>
        <% end %>
      </li>
    </ul>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  <footer>
    &copy; 2018 Bike Berlin
  </footer>

</body>
</html>